language: python
python:
- '2.7'

script:
- python scripts/gendocs.py

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
        branch: master
